"""
Copyright © IQ.Lvbs, apart of Project Teal Lvbs, All Rights Reserved, licensed under https://konn3kt.com/tos/
"""

import math
import time
import pyray as rl
from typing import Union
from enum import Enum
from collections.abc import Callable
from iqpilot.system.ui.widgets import Widget
from iqpilot.system.ui.widgets.label import MiciLabel
from iqpilot.system.ui.widgets.scroller import DO_ZOOM
from iqpilot.system.ui.lib.text_measure import measure_text_cached
from iqpilot.system.ui.lib.application import gui_app, FontWeight, MousePos
from iqpilot.common.filter_simple import BounceFilter

try:
  from iqpilot.ui.theme import NeonTheme
except ImportError:
  # Fallback theme if iqpilot layer not available
  class _FallbackTheme:
    def glow(self, alpha=255): return rl.Color(0, 255, 245, alpha)
    def glow_mid(self, alpha=130): return rl.Color(0, 255, 245, alpha)
    def glow_outer(self, alpha=45): return rl.Color(0, 255, 245, alpha)
    def bg(self): return rl.Color(0, 26, 25, 255)
    def bg_pressed(self): return rl.Color(0, 33, 32, 255)
  NeonTheme = _FallbackTheme()

SCROLLING_SPEED_PX_S = 50
COMPLICATION_SIZE    = 36
LABEL_COLOR          = rl.Color(255, 255, 255, int(255 * 0.9))
LABEL_HORIZONTAL_PADDING = 40
COMPLICATION_GREY    = rl.Color(0xAA, 0xAA, 0xAA, 255)
PRESSED_SCALE = 1.15 if DO_ZOOM else 1.07


class ScrollState(Enum):
  PRE_SCROLL = 0
  SCROLLING = 1
  POST_SCROLL = 2


class BigButton(Widget):
  """A lightweight stand-in for the Qt BigButton, drawn & updated each frame."""

  def __init__(self, text: str, value: str = "", icon: Union[str, rl.Texture] = "", icon_size: tuple[int, int] = (64, 64)):
    super().__init__()
    self.set_rect(rl.Rectangle(0, 0, 402, 180))
    self.text = text
    self.value = value
    self._icon_size = icon_size
    self.set_icon(icon)

    self._scale_filter = BounceFilter(1.0, 0.1, 1 / gui_app.target_fps)

    self._rotate_icon_t: float | None = None

    self._label_font = gui_app.font(FontWeight.DISPLAY)
    self._value_font = gui_app.font(FontWeight.ROMAN)

    self._label = MiciLabel(text, font_size=self._get_label_font_size(), width=int(self._rect.width - LABEL_HORIZONTAL_PADDING * 2),
                            font_weight=FontWeight.DISPLAY, color=LABEL_COLOR,
                            alignment_vertical=rl.GuiTextAlignmentVertical.TEXT_ALIGN_BOTTOM, wrap_text=True)
    self._sub_label = MiciLabel(value, font_size=COMPLICATION_SIZE, width=int(self._rect.width - LABEL_HORIZONTAL_PADDING * 2),
                                font_weight=FontWeight.ROMAN, color=COMPLICATION_GREY,
                                alignment_vertical=rl.GuiTextAlignmentVertical.TEXT_ALIGN_BOTTOM, wrap_text=True)

    self._load_images()

    # internal state
    self._scroll_offset = 0       # in pixels
    self._needs_scroll = measure_text_cached(self._label_font, text, self._get_label_font_size()).x + 25 > self._rect.width
    self._scroll_timer = 0
    self._scroll_state = ScrollState.PRE_SCROLL

  def set_icon(self, icon: Union[str, rl.Texture]):
    self._txt_icon = gui_app.texture(icon, *self._icon_size) if isinstance(icon, str) and len(icon) else icon

  def set_rotate_icon(self, rotate: bool):
    if rotate and self._rotate_icon_t is not None:
      return
    self._rotate_icon_t = rl.get_time() if rotate else None

  def _load_images(self):
    self._txt_default_bg = gui_app.texture("icons_mici/buttons/button_rectangle.png", 402, 180)
    self._txt_pressed_bg = gui_app.texture("icons_mici/buttons/button_rectangle_pressed.png", 402, 180)
    self._txt_disabled_bg = gui_app.texture("icons_mici/buttons/button_rectangle_disabled.png", 402, 180)
    self._txt_hover_bg = gui_app.texture("icons_mici/buttons/button_rectangle_hover.png", 402, 180)

  def _get_label_font_size(self):
    if len(self.text) < 12:
      font_size = 64
    elif len(self.text) < 17:
      font_size = 48
    elif len(self.text) < 20:
      font_size = 42
    else:
      font_size = 36

    if self.value:
      font_size -= 20

    return font_size

  def set_text(self, text: str):
    self.text = text
    self._label.set_text(text)

  def set_value(self, value: str):
    self.value = value
    self._sub_label.set_text(value)

  def get_value(self) -> str:
    return self.value

  def get_text(self):
    return self.text

  def _update_state(self):
    # hold on text for a bit, scroll, hold again, reset
    if self._needs_scroll:
      """`dt` should be seconds since last frame (rl.get_frame_time())."""
      # TODO: this comment is generated by GPT, prob wrong and misused
      dt = rl.get_frame_time()

      self._scroll_timer += dt
      if self._scroll_state == ScrollState.PRE_SCROLL:
        if self._scroll_timer < 0.5:
          return
        self._scroll_state = ScrollState.SCROLLING
        self._scroll_timer = 0

      elif self._scroll_state == ScrollState.SCROLLING:
        self._scroll_offset -= SCROLLING_SPEED_PX_S * dt
        # reset when text has completely left the button + 50 px gap
        # TODO: use global constant for 30+30 px gap
        # TODO: add std Widget padding option integrated into the self._rect
        full_len = measure_text_cached(self._label_font, self.text, self._get_label_font_size()).x + 30 + 30
        if self._scroll_offset < (self._rect.width - full_len):
          self._scroll_state = ScrollState.POST_SCROLL
          self._scroll_timer = 0

      elif self._scroll_state == ScrollState.POST_SCROLL:
        # wait for a bit before starting to scroll again
        if self._scroll_timer < 0.75:
          return
        self._scroll_state = ScrollState.PRE_SCROLL
        self._scroll_timer = 0
        self._scroll_offset = 0

  def _render(self, _):
    # draw _txt_default_bg
    txt_bg = self._txt_default_bg
    if not self.enabled:
      txt_bg = self._txt_disabled_bg
    elif self.is_pressed:
      txt_bg = self._txt_hover_bg

    scale = self._scale_filter.update(PRESSED_SCALE if self.is_pressed else 1.0)
    btn_x = self._rect.x + (self._rect.width * (1 - scale)) / 2
    btn_y = self._rect.y + (self._rect.height * (1 - scale)) / 2
    rl.draw_texture_ex(txt_bg, (btn_x, btn_y), 0, scale, rl.WHITE)

    # LABEL ------------------------------------------------------------------
    lx = self._rect.x + LABEL_HORIZONTAL_PADDING
    ly = btn_y + self._rect.height - 33  # - 40# - self._get_label_font_size() / 2

    if self.value:
      self._sub_label.set_position(lx, ly)
      ly -= self._sub_label.font_size + 9
      self._sub_label.render()

    label_color = LABEL_COLOR if self.enabled else rl.Color(255, 255, 255, int(255 * 0.35))
    self._label.set_color(label_color)
    self._label.set_position(lx, ly)
    self._label.render()

    # ICON -------------------------------------------------------------------
    if self._txt_icon:
      rotation = 0
      if self._rotate_icon_t is not None:
        rotation = (rl.get_time() - self._rotate_icon_t) * 180

      # drop top right with 30px padding
      x = self._rect.x + self._rect.width - 30 - self._txt_icon.width / 2
      y = self._rect.y + 30 + self._txt_icon.height / 2
      source_rec = rl.Rectangle(0, 0, self._txt_icon.width, self._txt_icon.height)
      dest_rec = rl.Rectangle(int(x), int(y), self._txt_icon.width, self._txt_icon.height)
      origin = rl.Vector2(self._txt_icon.width / 2, self._txt_icon.height / 2)
      rl.draw_texture_pro(self._txt_icon, source_rec, dest_rec, origin, rotation, rl.WHITE)


# TODO: param control base class
_CHIP_BG         = rl.Color(0x30, 0x30, 0x30, 230)
_CHIP_TEXT_COLOR = rl.Color(0xDD, 0xDD, 0xDD, 255)
_CHIP_H          = 28
_CHIP_FONT_SIZE  = 18
_CHIP_H_PAD      = 10
_CHIP_V_PAD      = 5
_CHIP_RADIUS     = 0.5
_CHIP_SPACING    = 8
_NEON_CORNER_ROUND = 0.28
_NEON_CARD_PAD     = 18


def _draw_neon_glow_halo(rect: rl.Rectangle, intensity: float = 1.0):
  segs      = 8
  roundness = _NEON_CORNER_ROUND
  for expand, alpha in [
    (14, int(18  * intensity)),
    (12, int(28  * intensity)),
    (10, int(40  * intensity)),
    (8,  int(55  * intensity)),
    (6,  int(72  * intensity)),
    (4,  int(95  * intensity)),
    (2,  int(120 * intensity)),
  ]:
    ex = rl.Rectangle(
      rect.x - expand, rect.y - expand,
      rect.width + expand * 2, rect.height + expand * 2,
    )
    rl.draw_rectangle_rounded(ex, roundness, segs, NeonTheme.glow_outer(alpha))


def _draw_neon_glow_border(rect: rl.Rectangle, intensity: float = 1.0):
  segs      = 8
  roundness = _NEON_CORNER_ROUND
  rl.draw_rectangle_rounded_lines_ex(rect, roundness, segs, 2.5,
                                     NeonTheme.glow(int(255 * intensity)))
  rl.draw_rectangle_rounded_lines_ex(rect, roundness, segs, 1.0,
                                     rl.Color(255, 255, 255, int(180 * intensity)))


def _neon_title_font_size(text: str, has_chips: bool) -> int:
  if len(text) < 10:
    size = 52
  elif len(text) < 14:
    size = 42
  elif len(text) < 18:
    size = 36
  else:
    size = 30
  if has_chips:
    size = min(size, 36)
  return size


class NeonBigButton(Widget):

  CARD_W = 310
  CARD_H = 160

  def __init__(self, title: str, chips: list[str] | None = None,
               click_callback: Callable | None = None):
    super().__init__()
    self._title_text       = title
    self._chips: list[str] = chips or []
    self._click_callback   = click_callback
    self._born: float      = time.monotonic()

    self.set_rect(rl.Rectangle(0, 0, self.CARD_W, self.CARD_H))

    self._label = MiciLabel(
      title,
      font_size=_neon_title_font_size(title, bool(chips)),
      width=self.CARD_W - _NEON_CARD_PAD * 2,
      font_weight=FontWeight.DISPLAY,
      color=LABEL_COLOR,
      alignment_vertical=rl.GuiTextAlignmentVertical.TEXT_ALIGN_TOP,
      wrap_text=True,
      elide_right=False,
    )
    self._chip_font = gui_app.font(FontWeight.MEDIUM)

  def set_chips(self, chips: list[str]):
    self._chips = chips
    # Re-size title now that we know if chips are present
    self._label.set_font_size(_neon_title_font_size(self._title_text, bool(chips)))

  def set_click_callback(self, cb: Callable | None):
    self._click_callback = cb

  def _glow_intensity(self) -> float:
    t = time.monotonic() - self._born
    return 0.65 + 0.35 * (0.5 + 0.5 * math.sin(t * 5.0))

  def _render_chips(self, start_x: float, start_y: float):
    x = start_x
    for chip in self._chips:
      text_w = int(measure_text_cached(self._chip_font, chip, _CHIP_FONT_SIZE).x)
      w      = text_w + _CHIP_H_PAD * 2
      rl.draw_rectangle_rounded(rl.Rectangle(x, start_y, w, _CHIP_H),
                                 _CHIP_RADIUS, 4, _CHIP_BG)
      text_y = start_y + (_CHIP_H - _CHIP_FONT_SIZE) // 2
      rl.draw_text_ex(
        self._chip_font,
        chip,
        rl.Vector2(x + _CHIP_H_PAD, text_y),
        _CHIP_FONT_SIZE,
        0,
        _CHIP_TEXT_COLOR,
      )
      x += w + _CHIP_SPACING

  def _render(self, rect: rl.Rectangle) -> None:
    intensity = self._glow_intensity()
    _draw_neon_glow_halo(rect, intensity)
    bg = NeonTheme.bg_pressed() if self.is_pressed else NeonTheme.bg()
    rl.draw_rectangle_rounded(rect, _NEON_CORNER_ROUND, 6, bg)
    _draw_neon_glow_border(rect, intensity)
    chips_h  = (_CHIP_H + 6) if self._chips else 0
    title_rect = rl.Rectangle(
      rect.x + _NEON_CARD_PAD,
      rect.y + _NEON_CARD_PAD,
      rect.width - _NEON_CARD_PAD * 2,
      rect.height - _NEON_CARD_PAD - chips_h,
    )
    label_color = LABEL_COLOR if self.enabled else rl.Color(255, 255, 255, int(255 * 0.35))
    self._label.set_color(label_color)
    self._label.render(title_rect)
    if self._chips:
      chip_y = rect.y + rect.height - _CHIP_H - _NEON_CARD_PAD // 2
      self._render_chips(rect.x + _NEON_CARD_PAD, chip_y)

  def _handle_mouse_release(self, mouse_pos: MousePos):
    super()._handle_mouse_release(mouse_pos)
    if self._click_callback:
      self._click_callback()
